[build]
functions = "netlify/functions"
publish = "dist"
command = "npm run build"

[[redirects]]
from = "/api/upload"
to = "/.netlify/functions/upload"
status = 200

[[redirects]]
from = "/api/download/*"
to = "/.netlify/functions/download"
status = 200

[[redirects]]
from = "/download/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"